version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: minilink-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - minilink_db_data:/var/lib/postgresql/data

volumes:
  minilink_db_data:
